export const COLOURS = {
  white: "#ffffff",
  black: "#000000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#0043F9",
  backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#0C004D",
  lemonGreen: "#C1E7D3"
};

export const Items = [
  {
    id: "bd7acbea-c1b1-46c2-aed5-3abb",
    productImage: require("../../assets/pat.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton. Is also water proof",
    productPrice: 199,
    ratings: "4 stars",
    location: "Lapaz",
    isAvailable: true,
    productImageList: [
      require("../../assets/pat.jpg"),
      require("../../assets/pat.jpg"),
      require("../../assets/pat.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1-c2-aed5-d53abb28ba",
    productImage: require("../../assets/nike1.jpeg"),
    productName: "Nike",
    description: "This is one of the best you can find on this plat form ",
    productPrice: 599,
    location: "kawshiman",
    isAvailable: true,
    productImageList: [
      require("../../assets/nike1.jpeg"),
      require("../../assets/nike1.jpeg"),
      require("../../assets/nike1.jpeg"),
    ],
  },
  {
    id: "bd7acbea-c1b1-46c2-aed5-3aabb",
    productImage: require("../../assets/jacket.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton.",
    productPrice: 300,
    location: "achimota",
    isAvailable: true,
    productImageList: [
      require("../../assets/jacket.jpg"),
      require("../../assets/jacket.jpg"),
      require("../../assets/jacket.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1b1-46sasc2-aed5-3abb",
    productImage: require("../../assets/revolt.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton. Is also water proof",
    productPrice: 400,
    ratings: "4 stars",
    location: "Lapaz",
    isAvailable: true,
    productImageList: [
      require("../../assets/revolt.jpg"),
      require("../../assets/revolt.jpg"),
      require("../../assets/revolt.jpg"),
      require("../../assets/revolt.jpg"),
    ],
  },

  {
    id: "bd7acbea-c1b1-46c2-aeeed5-3a53abb",
    productImage: require("../../assets/revolt.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton.",
    productPrice: 200,
    location: "achimota",
    isAvailable: true,
    productImageList: [
      require("../../assets/revolt.jpg"),
      require("../../assets/revolt.jpg"),
      require("../../assets/revolt.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1b1-46c2-aed5q-3abb",
    productImage: require("../../assets/paul.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton. Is also water proof",
    productPrice: 599,
    ratings: "4 stars",
    location: "Lapaz",
    isAvailable: true,
    productImageList: [
      require("../../assets/paul.jpg"),
      require("../../assets/paul.jpg"),
      require("../../assets/paul.jpg"),
      require("../../assets/paul.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1-c2-aed5-drr53abb28ba",
    productImage: require("../../assets/usama.jpg"),
    productName: "Nike",
    description: "This is one of the best you can find on this plat form ",
    productPrice: 499,
    location: "kawshiman",
    isAvailable: true,
    productImageList: [
      require("../../assets/usama.jpg"),
      require("../../assets/usama.jpg"),
      require("../../assets/usama.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1bw1-46c2-aed5-3a53abb",
    productImage: require("../../assets/pat.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton.",
    productPrice: 500,
    location: "achimota",
    isAvailable: true,
    productImageList: [
      require("../../assets/pat.jpg"),
      require("../../assets/pat.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1-c2-aeeewd5-d53abb28ba",
    productImage: require("../../assets/wengan.jpg"),
    productName: "Nike",
    description: "This is one of the best you can find on this plat form ",
    productPrice: 900,
    location: "kawshiman",
    isAvailable: true,
    productImageList: [
      require("../../assets/wengan.jpg"),
      require("../../assets/wengan.jpg"),
      require("../../assets/wengan.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1-c2-aed5-d53abb2e8ba",
    productImage: require("../../assets/nike1.jpeg"),
    productName: "Nike",
    description: "This is one of the best you can find on this plat form ",
    productPrice: 450,
    location: "kawshiman",
    isAvailable: true,
    productImageList: [
      require("../../assets/nike1.jpeg"),
      require("../../assets/nike1.jpeg"),
      require("../../assets/nike1.jpeg"),
    ],
  },
  {
    id: "bd7qacbea-c1b1-46c2-aed5-3a53abb",
    productImage: require("../../assets/jacket.jpg"),
    productName: "Black Jacket",
    location: "kawshiman",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton.",
    productPrice: 1000,
    location: "achimota",
    isAvailable: true,
    productImageList: [
      require("../../assets/jacket.jpg"),
      require("../../assets/jacket.jpg"),
      require("../../assets/jacket.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1b1-46c2ww-aed5-3abb",
    productImage: require("../../assets/pat.jpg"),
    productName: "Black Jacket",
    location: "kawshiman",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton. Is also water proof",
    productPrice: 600,
    ratings: "4 stars",
    location: "Lapaz",
    isAvailable: true,
    productImageList: [
      require("../../assets/pat.jpg"),
      require("../../assets/pat.jpg"),
    ],
  },
  {
    id: "bd7acbea-c1-c2-aed5-db28ba",
    productImage: require("../../assets/nike1.jpeg"),
    productName: "Nike",
    description: "This is one of the best you can find on this plat form ",
    productPrice: "$299",
    location: "kawshiman",
    isAvailable: true,
    productImageList: [
      require("../../assets/nike1.jpeg"),
      require("../../assets/nike1.jpeg"),
      require("../../assets/nike1.jpeg"),
    ],
  },
  {
    id: "bd7acbea-c1b1-46c2-aed5-3a3abb",
    productImage: require("../../assets/paul.jpg"),
    productName: "Black Jacket",
    description:
      "This is one of the best you can find on this plat form .Is made of pure cotton.",
    productPrice: 200,
    location: "achimota",
    isAvailable: true,
    productImageList: [
      require("../../assets/paul.jpg"),
      require("../../assets/paul.jpg"),
      require("../../assets/paul.jpg"),
    ],
  },
  {
    id: "rr232343",
    category: "product",
    productName: "MI Super Bass Bluetooth Wireless Headphones",
    productPrice: 1799,
    description:
      "Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control",
    isOff: true,
    offPercentage: 10,
    productImage: require("../../assets/images/products/Mi1.png"),
    isAvailable: true,
    location: "kawshiman",
    productImageList: [
      require("../../assets/images/products/Mi1.png"),
      require("../../assets/images/products/Mi2.png"),
      require("../../assets/images/products/Mi3.png"),
    ],
  },
  {
    id: "sdfd2123323",
    category: "product",
    productName: "boAt Rockerz 450 Bluetooth Headphone",
    productPrice: 1499,
    location: "kawshiman",
    description:
      "boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.",
    isOff: false,
    productImage: require("../../assets/images/products/boat1.png"),
    isAvailable: true,
    productImageList: [
      require("../../assets/images/products/boat1.png"),
      require("../../assets/images/products/boat2.png"),
      require("../../assets/images/products/boat3.png"),
    ],
  },
  {
    id: "svd334223",
    category: "accessory",
    productName: "boAt Airdopes 441",
    productPrice: 1999,
    location: "kawshiman",
    description:
      "Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS",
    isOff: true,
    offPercentage: 18,
    productImage: require("../../assets/images/accessories/boatairpods1.png"),
    isAvailable: true,
    productImageList: [
      require("../../assets/images/accessories/boatairpods1.png"),
      require("../../assets/images/accessories/boatairpods2.png"),
      require("../../assets/images/accessories/boatairpods3.png"),
    ],
  },
  {
    id: "hdhdu7783",
    category: "accessory",
    productName: "boAt Bassheads 242",
    productPrice: 399,
    location: "kawshiman",
    description:
      "Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.",
    isOff: false,
    productImage: require("../../assets/images/accessories/boatbassheads1.png"),
    isAvailable: true,
    productImageList: [
      require("../../assets/images/accessories/boatbassheads1.png"),
      require("../../assets/images/accessories/boatbassheads2.png"),
      require("../../assets/images/accessories/boatbassheads3.png"),
    ],
  },
  {
    id: "gdu7874",
    category: "accessory",
    productName: "boAt Rockerz 255 Pro+",
    productPrice: 1499,
    description:
      "The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.",
    isOff: false,
    productImage: require("../../assets/images/accessories/boatrockerz1.png"),
    isAvailable: true,
    productImageList: [
      require("../../assets/images/accessories/boatrockerz1.png"),
      require("../../assets/images/accessories/boatrockerz2.png"),
      require("../../assets/images/accessories/boatrockerz3.png"),
    ],
    location: "kawshiman",
  },
  {
    id: "28774eg46",
    category: "accessory",
    productName: "Boult Audio AirBass Propods TWS",
    productPrice: 1299,
    description:
      "One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant",
    isOff: false,
    productImage: require("../../assets/images/accessories/boultairbass1.png"),
    isAvailable: true,
    location: "kawshiman",
    productImageList: [
      require("../../assets/images/accessories/boultairbass1.png"),
      require("../../assets/images/accessories/boultairbass2.png"),
      require("../../assets/images/accessories/boultairbass3.png"),
      require("../../assets/images/accessories/boultairbass3.png"),
    ],
  },
];